### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "asdf@asdf.com",
  "password": "asdfghjkl"
}

### Create a new user (with error)
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "asdfasdf.com",
  "password": "asdfghjkl"
}

### Create a new user (with error no password)
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "asdf@asdf.com"
}