### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "aasdf1@asdf1.com",
  "password": "asdfghjkl"
}

### Sign in user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "aasdf1@asdf1.com",
  "password": "asdfghjkl"
}

### Get Current User
GET http://localhost:3000/auth/whoami/

### Sign OUT
POST http://localhost:3000/auth/signout

### Create a new user (with error)
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "asdfasdf.com",
  "password": "asdfghjkl"
}

### Create a new user (with error no password)
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "asdf@asdf.com"
}

### Find a particular user with a given ID
GET http://localhost:3000/auth/1

### Find all users with a given email
GET http://localhost:3000/auth/?email=asdf@asdf.com

### Delete a User by id
DELETE http://localhost:3000/auth/3

### Update a User
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
  "email": "teste@teste.com"
}